CallBlocker/Models/AccountViewModels/SaveSettingsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CallBlocker.Models.AccountViewModels
{
    public class LoginWithSettingsViewModel
    {
        public string AdminEmail { get; set; }
        public string NotificationTime { get; set; }
    }
}

CallBlocker/Controllers/V1/StatisticSettingsController.cs
using System;
using System.Threading.Tasks;
using CallBlocker.Models.AccountFilters;
using CallBlocker.Models.AccountViewModels;
using CallBlocker.Models.Settings;
using CallBlocker.Repositories.Account;
using CallBlocker.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CallBlocker.Controllers.V1
{
    [Produces("application/json")]
    [Route("api/Settings")]
    public class StatisticSettingsController : Controller
    {
        private readonly IAccountRepository _accountRepository;
        private readonly ISettingsService _settingsService;

        public StatisticSettingsController(IAccountRepository accountRepository, ISettingsService settingsService)
        {
            _accountRepository = accountRepository;
            _settingsService = settingsService;
        }

        [ResponseCache(NoStore =true, Location =ResponseCacheLocation.None)]
        [AccountAuthentification]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            TodayStatisticSettings todayStatisticSettings = new TodayStatisticSettings();

            todayStatisticSettings.AdminEmails = await _accountRepository.GetAdminEmails();
            var cronExpression = await QuartzServicesUtilities.GetJobInterval();

            _settingsService.GetTriggerFireTime(cronExpression, out string hours, out string minutes);
            todayStatisticSettings.SendTodayStatisticHours = hours;
            todayStatisticSettings.SendTodayStatisticMinutes = minutes;

            return View(todayStatisticSettings);
        }

        [Route("Login")]
        [HttpGet]
        public async Task<IActionResult> Authorization()
        {
            return View();
        }

        [Route("Login")]
        [HttpPost]
        public async Task<IActionResult> AuthorizationPost(LoginWithSettingsViewModel model)
        {
            if (string.IsNullOrEmpty(model.AdminEmail))
                return View("Authorization");

            var emailIsValid = await _accountRepository.EmailIsValid(model.AdminEmail);

            if (emailIsValid == false)
            {
                ViewBag.Error = "Couldn't find your Call Verify Account";
                return View("Authorization");
            }

            CookieOptions cookieOptions = new CookieOptions();
            cookieOptions.Expires = new DateTimeOffset(DateTime.Now.AddMinutes(10));
            Response.Cookies.Append("CallBlockerValidationKey", model.AdminEmail, cookieOptions);
            return RedirectToAction("Index");
        }

        [Route("Logout")]
        [HttpGet]
        public IActionResult Logout()
        {
            var cookie = Request.Cookies;
            if (cookie != null)
            {
                Response.Cookies.Delete("CallBlockerValidationKey");
            }
            return RedirectToAction("Authorization");
        }

        [Route("SaveSettings")]
        [AccountAuthentification]
        [HttpPost]
        public async Task<IActionResult> SaveSettings([FromBody]TodayStatisticSettings statisticModel)
        {
            var adminEmailFromCookie = Request.Cookies["CallBlockerValidationKey"];
            bool emailIsValid;
            try
            {
                emailIsValid = await _accountRepository.EmailIsValid(adminEmailFromCookie);

                await _settingsService.SaveAdminEmails(statisticModel.AdminEmailsString);
                await _settingsService.ResheduleJobWithNewTime(statisticModel.SendTodayStatisticHours, statisticModel.SendTodayStatisticMinutes);
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
                ViewBag.Success = false;
                return PartialView();
            }

            if (!emailIsValid)
            {
                ViewBag.Message = "You are not Admin!";
                ViewBag.Success = false;
                return PartialView();
            }

            ViewBag.Message = "Saved!";
            ViewBag.Success = true;

            return PartialView();
        }

        [Route("Get")]
        [HttpGet]
        public async Task<IActionResult> Get()
        {
            var adminEmails = await _accountRepository.GetAdminEmails();
            var cronExpression = await QuartzServicesUtilities.GetJobInterval();

            _settingsService.GetTriggerFireTime(cronExpression, out string hours, out string minutes);

            return Json(new { hours, minutes, adminEmails = string.Join(";", adminEmails) });
        }
    }
}

CallBlocker/Controllers/V2/StatisticSettingsController.cs
using System;
using System.Threading.Tasks;
using CallBlocker.Models.AccountFilters;
using CallBlocker.Models.AccountViewModels;
using CallBlocker.Models.Settings;
using CallBlocker.Repositories.Account;
using CallBlocker.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CallBlocker.Controllers.V2
{
    [Produces("application/json")]
    [Route("api/v2/Settings")]
    public class StatisticSettingsController : Controller
    {
        private readonly IAccountRepository _accountRepository;
        private readonly ISettingsService _settingsService;

        public StatisticSettingsController(IAccountRepository accountRepository, ISettingsService settingsService)
        {
            _accountRepository = accountRepository;
            _settingsService = settingsService;
        }

        [ResponseCache(NoStore =true, Location =ResponseCacheLocation.None)]
        [AccountAuthentification]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            TodayStatisticSettings todayStatisticSettings = new TodayStatisticSettings();

            todayStatisticSettings.AdminEmails = await _accountRepository.GetAdminEmails();
            var cronExpression = await QuartzServicesUtilities.GetJobInterval();

            _settingsService.GetTriggerFireTime(cronExpression, out string hours, out string minutes);
            todayStatisticSettings.SendTodayStatisticHours = hours;
            todayStatisticSettings.SendTodayStatisticMinutes = minutes;

            return View(todayStatisticSettings);
        }

        [Route("Login")]
        [HttpGet]
        public async Task<IActionResult> Authorization()
        {
            return View();
        }

        [Route("Login")]
        [HttpPost]
        public async Task<IActionResult> AuthorizationPost(LoginWithSettingsViewModel model)
        {
            if (string.IsNullOrEmpty(model.AdminEmail))
                return View("Authorization");

            var emailIsValid = await _accountRepository.EmailIsValid(model.AdminEmail);

            if (emailIsValid == false)
            {
                ViewBag.Error = "Couldn't find your Call Verify Account";
                return View("Authorization");
            }

            CookieOptions cookieOptions = new CookieOptions();
            cookieOptions.Expires = new DateTimeOffset(DateTime.Now.AddMinutes(10));
            Response.Cookies.Append("CallBlockerValidationKey", model.AdminEmail, cookieOptions);
            return RedirectToAction("Index");
        }

        [Route("Logout")]
        [HttpGet]
        public IActionResult Logout()
        {
            var cookie = Request.Cookies;
            if (cookie != null)
            {
                Response.Cookies.Delete("CallBlockerValidationKey");
            }
            return RedirectToAction("Authorization");
        }

        [Route("SaveSettings")]
        [AccountAuthentification]
        [HttpPost]
        public async Task<IActionResult> SaveSettings([FromBody]TodayStatisticSettings statisticModel)
        {
            var adminEmailFromCookie = Request.Cookies["CallBlockerValidationKey"];
            bool emailIsValid;
            try
            {
                emailIsValid = await _accountRepository.EmailIsValid(adminEmailFromCookie);

                await _settingsService.SaveAdminEmails(statisticModel.AdminEmailsString);
                await _settingsService.ResheduleJobWithNewTime(statisticModel.SendTodayStatisticHours, statisticModel.SendTodayStatisticMinutes);
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
                ViewBag.Success = false;
                return PartialView();
            }

            if (!emailIsValid)
            {
                ViewBag.Message = "You are not Admin!";
                ViewBag.Success = false;
                return PartialView();
            }

            ViewBag.Message = "Saved!";
            ViewBag.Success = true;

            return PartialView();
        }

        [Route("Get")]
        [HttpGet]
        public async Task<IActionResult> Get()
        {
            var adminEmails = await _accountRepository.GetAdminEmails();
            var cronExpression = await QuartzServicesUtilities.GetJobInterval();

            _settingsService.GetTriggerFireTime(cronExpression, out string hours, out string minutes);

            return Json(new { hours, minutes, adminEmails = string.Join(";", adminEmails) });
        }
    }
}

CallBlocker/Views/StatisticSettings/Authorization.cshtml
@model CallBlocker.Models.AccountViewModels.LoginWithSettingsViewModel
@{
    Layout = "~/Views/StatisticSettings/_LayoutSettings.cshtml";
}
<div class="content-container">
    @using (Html.BeginForm("AuthorizationPost", "StatisticSettings", FormMethod.Post))
    {
        <div class="registrationform-title">
            <p>Enter your email</p>
        </div>
        <div class="registrationform-message">
            <div>
                <p>@ViewBag.Error</p>
            </div>
        </div>
        @Html.TextBoxFor(model => model.AdminEmail, new { @type = "email", @class = "registrationform-input", @placeholder = "example@mail.com" })

        <div class="registrationform-line">
        </div>
        <input id="inputSignin" type="submit" value="Sign in" class="btn btn-primary btn-lg" />
    }
    <div id="signInInfoDiv" class="registrationform-progress-message">
    </div>
</div>


<script src="~/js/authorization.js" asp-append-version="true"></script>

CallBlocker/Views/StatisticSettings/Index.cshtml
@model CallBlocker.Models.Settings.TodayStatisticSettings
@{
    Layout = "~/Views/StatisticSettings/_LayoutSettings.cshtml";
}
<div class="index-signout-container">
    @Html.ActionLink("Sign out", "Logout", "StatisticSettings", null, new { @class = "signout-link" })
</div>
<div class="content-container">
    <div class="text">
        <p>
            Daily statistics sent at <input id="sendTodayStatisticHoursInput" type="number" name="time" min="00" max="23" onblur="CheckHoursMinutesInput()" onclick="ShowInputById(inputSaveInForm)" class="index-input-time" value="@Model.SendTodayStatisticHours" />  :
            <input id="sendTodayStatisticMinutesInput" type="number" name="time" min="00" max="59" onblur="CheckHoursMinutesInput()" onclick="ShowInputById(inputSaveInForm)" class="index-input-time" value="@Model.SendTodayStatisticMinutes" /> Arizona time
        </p>
    </div>
    <div class="index-line">
    </div>
    <div class="text">
        <p>Admin Emails:</p>
    </div>
    <table class="index-table">
        <tbody class="index-container-emails">
            <tr>
                <td>
                    <div id="container" class="index-container-emails-add-content">
                    </div>
                    <div id="inputEmailDiv" class="index-container-email-input">
                        <textarea id="inputEmailTxtArea" placeholder="example@mail.com" rows="1" class="index-container-email-input-textarea"></textarea>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
    <div style="height:80px; margin-top:20px">
        <input id="inputSaveInForm" type="hidden" value="Save" class="btn btn-primary btn-lg" onclick="SaveTodayStatisticSettings()" />
    </div>
    <div id="result" style="height:50px">
    </div>
</div>



<script src="~/js/index.js" asp-append-version="true"></script>

CallBlocker/Views/StatisticSettings/SaveSettings.cshtml
@if (ViewBag.Success)
{
    <span style="color:darkgreen; font-size:20px">@ViewBag.Message</span><br />
}
else
{
    <span style="color:darkred; font-size:20px">@ViewBag.Message</span><br />
}

CallBlocker/Views/StatisticSettings/_LayoutSettings.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   

    <title>Call Blocker Settings</title>

    <environment include="Development">

        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/_layout_settings.css" />
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/_layout_settings.css" asp-append-version="true" />
    </environment>

</head>
<body id="body">

    <div class="jumbotron text-center">
        <h1>Call Verify</h1>
        <h2>Settings</h2>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>  
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>


    @RenderSection("Scripts", required: false)

</body>
</html>